name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: macos-14
    steps:
      - name: Check out source
        uses: actions/checkout@v4
      - name: Run Swift tests
        run: swift test
